stages:
  - pipeline: 流水线-1
    steps:
      - name: test
        module: image
        image: go:1.18
        commands:
          - go env -w GO111MODULE=on
          - go env -w GOPROXY=https://goproxy.cn,direct
          - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -tags=jsoniter -o main ./main.go
          - ls
          - go run main.go