// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Admin is the golang structure of table admin for DAO operations like Where/Data.
type Admin struct {
	g.Meta    `orm:"table:admin, do:true"`
	Id        interface{} //
	UserName  interface{} //
	Password  interface{} //
	Avatar    interface{} //
	Income    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
