// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Comment is the golang structure of table comment for DAO operations like Where/Data.
type Comment struct {
	g.Meta    `orm:"table:comment, do:true"`
	Id        interface{} //
	UserId    interface{} //
	ProductId interface{} //
	Comment   interface{} //
	Type      interface{} // 0是差评，1是好评
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
