// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure of table product for DAO operations like Where/Data.
type Product struct {
	g.Meta             `orm:"table:product, do:true"`
	Id                 interface{} //
	ProductName        interface{} //
	PublisherName      interface{} //
	ProductImage       interface{} //
	ProductPrice       interface{} // 单位是分
	ProductStock       interface{} //
	ProductInstruction interface{} // 使用说明
	ProductType        interface{} //
	ProductDiscount    interface{} // 打折程度，1代表1折，以此类推
	PurchaseNumber     interface{} //
	BargainingAllowed  interface{} // 0代表不能议价，1代表可以议价
	WearDegree         interface{} // 磨损程度，用字符串表示
	Status             interface{} // -1代表审核不通过。0代表正在审核，1代表已发布
	CreatedAt          *gtime.Time //
	UpdatedAt          *gtime.Time //
}
