// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ReturnRequest is the golang structure of table return_request for DAO operations like Where/Data.
type ReturnRequest struct {
	g.Meta         `orm:"table:return_request, do:true"`
	Id             interface{} //
	UserName       interface{} //
	BusinessMan    interface{} //
	ProductName    interface{} //
	Money          interface{} //
	RequestMessage interface{} //
	RejectMessage  interface{} //
	Status         interface{} // -1不通过，0审核中，1通过
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
}
