// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta          `orm:"table:user, do:true"`
	Id              interface{} //
	Name            interface{} // 用户名，不代表真实姓名
	Password        interface{} //
	Avatar          interface{} //
	PhoneNumber     interface{} //
	Email           interface{} //
	City            interface{} //
	Gender          interface{} //
	BankNumber      interface{} //
	Income          interface{} // 单位为分
	BusinessLicense interface{} // 只有type为1时才有该字段
	BusinessLevel   interface{} // type为1时，有该字段，分5级
	Type            interface{} // 0代表普通用户，1代表商家,2是管理员
	Status          interface{} // -1代表审核不通过，0代表审核中，1代表审核通过
	FavorableRate   interface{} // 好评率
	CreatedAt       *gtime.Time //
	UpdatedAt       *gtime.Time //
}
