// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-study/internal/service/internal/dao/internal"
)

// internalReturnRequestDao is internal type for wrapping internal DAO implements.
type internalReturnRequestDao = *internal.ReturnRequestDao

// returnRequestDao is the data access object for table return_request.
// You can define custom methods on it to extend its functionality as you wish.
type returnRequestDao struct {
	internalReturnRequestDao
}

var (
	// ReturnRequest is globally public accessible object for table return_request operations.
	ReturnRequest = returnRequestDao{
		internal.NewReturnRequestDao(),
	}
)

// Fill with you ideas below.
