// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure for table product.
type Product struct {
	Id                 int         `json:"id"                  description:""`
	ProductName        string      `json:"product_name"        description:""`
	PublisherName      string      `json:"publisher_name"      description:""`
	ProductImage       string      `json:"product_image"       description:""`
	ProductPrice       int         `json:"product_price"       description:"单位是分"`
	ProductStock       int         `json:"product_stock"       description:""`
	ProductInstruction string      `json:"product_instruction" description:"使用说明"`
	ProductType        string      `json:"product_type"        description:""`
	ProductDiscount    int         `json:"product_discount"    description:"打折程度，1代表1折，以此类推"`
	PurchaseNumber     int         `json:"purchase_number"     description:""`
	BargainingAllowed  int         `json:"bargaining_allowed"  description:"0代表不能议价，1代表可以议价"`
	WearDegree         string      `json:"wear_degree"         description:"磨损程度，用字符串表示"`
	Status             int         `json:"status"              description:"-1代表审核不通过。0代表正在审核，1代表已发布"`
	CreatedAt          *gtime.Time `json:"created_at"          description:""`
	UpdatedAt          *gtime.Time `json:"updated_at"          description:""`
}
