// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id              int         `json:"id"               description:""`
	Name            string      `json:"name"             description:"用户名，不代表真实姓名"`
	Password        string      `json:"password"         description:""`
	Avatar          string      `json:"avatar"           description:""`
	PhoneNumber     string      `json:"phone_number"     description:""`
	Email           string      `json:"email"            description:""`
	City            string      `json:"city"             description:""`
	Gender          int         `json:"gender"           description:""`
	BankNumber      string      `json:"bank_number"      description:""`
	Income          int         `json:"income"           description:"单位为分"`
	BusinessLicense string      `json:"business_license" description:"只有type为1时才有该字段"`
	BusinessLevel   int         `json:"business_level"   description:"type为1时，有该字段，分5级"`
	Type            int         `json:"type"             description:"0代表普通用户，1代表商家,2是管理员"`
	Status          int         `json:"status"           description:"-1代表审核不通过，0代表审核中，1代表审核通过"`
	FavorableRate   string      `json:"favorable_rate"   description:"好评率"`
	CreatedAt       *gtime.Time `json:"created_at"       description:""`
	UpdatedAt       *gtime.Time `json:"updated_at"       description:""`
}
