// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TransactionDao is the data access object for table transaction.
type TransactionDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns TransactionColumns // columns contains all the column names of Table for convenient usage.
}

// TransactionColumns defines and stores column names for table transaction.
type TransactionColumns struct {
	Id            string //
	ProductName   string //
	Payer         string //
	Payee         string //
	Money         string // 单位为分
	IsReceive     string // 0未收货，1已收货
	BusinessLevel string //
	CreatedAt     string //
	UpdatedAt     string //
}

//  transactionColumns holds the columns for table transaction.
var transactionColumns = TransactionColumns{
	Id:            "id",
	ProductName:   "product_name",
	Payer:         "payer",
	Payee:         "payee",
	Money:         "money",
	IsReceive:     "is_receive",
	BusinessLevel: "business_level",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

// NewTransactionDao creates and returns a new DAO object for table data access.
func NewTransactionDao() *TransactionDao {
	return &TransactionDao{
		group:   "default",
		table:   "transaction",
		columns: transactionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TransactionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TransactionDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TransactionDao) Columns() TransactionColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TransactionDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TransactionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TransactionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
